### ISSUE TITLE
Some data are not labeled and they are not in the blacklist

### ISSUE THREAD

**Issue by weathon** [logic112358/RT-CAN#2]
For example:
![image](https://github.com/user-attachments/assets/6f763453-8a32-4700-9deb-5c018bc49616)

**Comment by A-new-b** [comment]
thanks for your reminder. We found we uploaded wrong version blacklist. The range "00223-00232" was blacklisted due to water spraying rather than gas release, while "00690-00720" was blacklisted because the gas traces were too weak. We will upload a new blacklist today.
